version: '3'
services:
  mp_frontend:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: mp_frontend
    hostname: mp_frontend
    volumes:
      - ../:/var/www/app
    ports:
      - "3000:3000"
    command: "bash"
    tty: true
