version: '3'
services:
  tc_frontend:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: tc_frontend
    hostname: tc_frontend
    volumes:
      - ../:/var/www/app
    ports:
      - "8080:8080"
    command: "bash"
    tty: true